apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  labels:
    app: demo
    style: web-server
spec:
  containers:
  - image: nginxinc/nginx-unprivileged
    name: nginx
      ports:
      - containerPort: 8080