apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
spec:
  replicas: 0
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo-pod
    spec:
      containers:
      - image: nginxinc/ngin-unprivileged
        name: nginx
        ports:
        - containerPort: 8080